accent = "#eadfca"
cursor = "#eadfca"
foreground = "#d8d1c3"
background = "#071923"
selection_foreground = "#071923"
selection_background = "#c6a15b"

color0 = "#071923"
color1 = "#b66a5d"
color2 = "#6f8f72"
color3 = "#c6a15b"
color4 = "#1f6f8b"
color5 = "#7b6f8f"
color6 = "#3b9aa8"
color7 = "#d8d1c3"
color8 = "#203846"
color9 = "#d18475"
color10 = "#8cab8d"
color11 = "#d8b86e"
color12 = "#2f86a3"
color13 = "#9586aa"
color14 = "#58b5bf"
color15 = "#eadfca"
