$activeBorderColor = rgb(41697c)
$inactiveBorderColor = rgb(071923)

general {
    gaps_in = 8
    gaps_out = 18
    border_size = 2
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

decoration {
    rounding = 12

    blur {
        enabled = true
        size = 6
        passes = 3
        contrast = 1.15
        brightness = 0.85
        vibrancy = 0.18
        vibrancy_darkness = 0.2
        noise = 0.04
        ignore_opacity = true
        new_optimizations = on
    }
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

layerrule {
    name = blur_waybar
    match:namespace = ^(waybar)$
    blur = true
    ignore_alpha = 0.1
}
